(function(b){b.fn.slideMenu=function(q){function r(c,d){if(c)if(typeof c=="object")if(Object.size(c)==Object.size(d)){for(var e in c)if(!d[e])return null;return c}return null}function s(c){var d={};b.each(c,function(e){d[e]=""});return d}var a={slideDuration:200,linkHiliteClass:null,sectHiliteClass:null,linkHiliteMap:null,sectHiliteMap:null,linkDefaultMap:null,sectDefaultMap:null,persistentHilite:false,autoPadLinksRight:null,fadeIn:null,fadeInDelay:300,relativeXOnResize:false,forceDispBlock:false,
forcePositionAbs:false,forceTextLeft:false,forceNoWrap:false,smoothAnchors:{speed:"fast",easing:null,redirect:false}};q&&b.extend(true,a,q);Object.equals=function(c,d){for(p in c)if(typeof d[p]=="undefined")return false;for(p in c)if(c[p])switch(typeof c[p]){case "object":if(!c[p].equals(d[p]))return false;break;case "function":if(typeof d[p]=="undefined"||p!="equals"&&c[p].toString()!=d[p].toString())return false;break;default:if(c[p]!=d[p])return false}else if(d[p])return false;for(p in d)if(typeof c[p]==
"undefined")return false;return true};Object.size=function(c){var d=0,e;for(e in c)c.hasOwnProperty(e)&&d++;return d};if(a.smoothAnchors){var t="html, body";b("html, body").each(function(){var c=b(this).attr("scrollTop");b(this).attr("scrollTop",c+1);if(b(this).attr("scrollTop")==c+1){t=this.nodeName.toLowerCase();b(this).attr("scrollTop",c);return false}});b("a").each(function(){var c=b(this).attr("href");if(c)if(c.indexOf("#")!=-1&&c.indexOf("#")==0){var d=c.split("#",2),e=b("a[name='"+d[1]+"']");
e&&b(this).click(function(){if(b(document).height()-e.offset().top>=b(window).height()||e.offset().top>b(window).height()||b(document).width()-e.offset().left>=b(window).width()||e.offset().left>b(window).width())b(t).animate({scrollTop:e.offset().top,scrollLeft:e.offset().left},a.smoothAnchors.speed,a.smoothAnchors.easing,function(){if(a.smoothAnchors.redirect)window.location=c});return false})}})}return this.each(function(){var c=b(this);a.forceDispBlock&&c.css("display","block");a.forcePositionAbs&&
c.css("position","absolute");a.forceTextLeft&&c.css("text-align","left");a.forceNoWrap&&c.css("white-space","nowrap");if(a.relativeXOnResize){var d=c.offset().left-b(window).width()/2;if(typeof a.relativeXOnResize=="number"){d=a.relativeXOnResize;c.css("left",b(window).width()/2+d)}b(window).resize(function(){c.css("left",b(window).width()/2+d)})}a.slideDuration=a.slideDuration||200;var e=parseInt(c.css("top")),l=e+b(document).scrollTop()+"px";c.animate({top:l},{duration:a.slideDuration,queue:false});
b(window).scroll(function(){l=e+b(document).scrollTop()+"px";c.animate({top:l},{duration:a.slideDuration,queue:false})});if(a.autoPadLinksRight){var j,k,m=[];switch(typeof a.autoPadLinksRight){case "string":k=j=a.autoPadLinksRight;break;case "object":j=a.autoPadLinksRight.measureSelector;k=a.autoPadLinksRight.paddingSelector;break;default:k=j="a"}c.find(j).each(function(){m.push(b(this).width())});var u=Math.max.apply(Math,m);c.find(k).each(function(f){b(this).css("padding-right",u-m[f]+parseInt(b(this).css("padding-right")))})}if(a.fadeIn){c.css("display",
"none").css("visibility","visible");c.delay(a.fadeInDelay).fadeIn(a.fadeIn)}if(a.sectHiliteClass||a.linkHiliteClass||a.sectHiliteMap||a.linkHiliteMap){var i=[];c.find('a[href^="#"]').each(function(f){i[f]=b(this).attr("href")});if(a.sectHiliteClass||a.linkHiliteClass){var g=null;c.find('a[href^="#"]').click(function(){g=b(this).attr("href");if(a.linkHiliteClass){c.find('a[href^="#"]').removeClass(a.linkHiliteClass);b(this).addClass(a.linkHiliteClass)}if(a.sectHiliteClass){b.each(i,function(f,h){b(h).removeClass(a.sectHiliteClass)});
b(g).addClass(a.sectHiliteClass)}});!a.persistentHilite&&a.smoothAnchors&&b(document).click(function(){b(g).click(function(f){f.stopPropagation()});g=null;c.find('a[href^="#"]').removeClass(a.linkHiliteClass);b.each(i,function(f,h){b(h).removeClass(a.sectHiliteClass)})})}if(a.sectHiliteMap||a.linkHiliteMap){var n=null,o=null;g=null;b('a[href^="#"]').first();if(a.linkHiliteMap)n=r(a.linkDefaultMap,a.linkHiliteMap)||s(a.linkHiliteMap);if(a.sectHiliteMap)o=r(a.sectDefaultMap,a.sectHiliteMap)||s(a.sectHiliteMap);
a.linkDefaultMap&&c.find('a[href^="#"]').css(a.linkDefaultMap);a.sectDefaultMap&&b.each(i,function(f,h){b(h).css(a.sectDefaultMap)});c.find('a[href^="#"]').click(function(){g=b(this).attr("href");if(a.linkHiliteMap){c.find('a[href^="#"]').css(n);b(this).css(a.linkHiliteMap)}if(a.sectHiliteMap){b.each(i,function(f,h){b(h).css(o)});b(g).css(a.sectHiliteMap)}});!a.persistentHilite&&a.smoothAnchors&&b(document).click(function(){b(g).click(function(f){f.stopPropagation()});g=null;c.find('a[href^="#"]').css(n);
b.each(i,function(f,h){b(h).css(o)})})}}})}})(jQuery);
