(function(b){b.fn.slideMenu=function(h){function o(a,b){if(a&&typeof a=="object"&&Object.size(a)==Object.size(b)){for(var d in a)if(!b[d])return null;return a}return null}function q(a){var f={};b.each(a,function(a){f[a]=""});return f}var a={slide:!0,slideDuration:200,linkHiliteClass:null,sectHiliteClass:null,linkHiliteMap:null,sectHiliteMap:null,linkDefaultMap:null,sectDefaultMap:null,persistentHilite:!1,autoPadLinksRight:null,fadeIn:null,fadeInDelay:300,relativeXOnResize:!1,forceDispBlock:!1,forcePositionAbs:!1,
forceTextLeft:!1,forceNoWrap:!1,smoothAnchors:{speed:"fast",easing:null,redirect:!1}};h&&b.extend(!0,a,h);Object.equals=function(a,b){for(p in a)if(typeof b[p]=="undefined")return!1;for(p in a)if(a[p])switch(typeof a[p]){case "object":if(!a[p].equals(b[p]))return!1;break;case "function":if(typeof b[p]=="undefined"||p!="equals"&&a[p].toString()!=b[p].toString())return!1;break;default:if(a[p]!=b[p])return!1}else if(b[p])return!1;for(p in b)if(typeof a[p]=="undefined")return!1;return!0};Object.size=
function(a){var b=0,d;for(d in a)a.hasOwnProperty(d)&&b++;return b};if(a.smoothAnchors){var r="html, body";b("html, body").each(function(){var a=b(this).attr("scrollTop");b(this).attr("scrollTop",a+1);if(b(this).attr("scrollTop")==a+1)return r=this.nodeName.toLowerCase(),b(this).attr("scrollTop",a),!1});b("a").each(function(){var c=b(this).attr("href");if(c&&c.indexOf("#")!=-1&&c.indexOf("#")==0){var f=c.split("#",2),d=b("a[name='"+f[1]+"']");d&&b(this).click(function(){(b(document).height()-d.offset().top>=
b(window).height()||d.offset().top>b(window).height()||b(document).width()-d.offset().left>=b(window).width()||d.offset().left>b(window).width())&&b(r).animate({scrollTop:d.offset().top,scrollLeft:d.offset().left},a.smoothAnchors.speed,a.smoothAnchors.easing,function(){if(a.smoothAnchors.redirect)window.location=c});return!1})}})}return this.each(function(){var c=b(this);a.forceDispBlock&&c.css("display","block");a.forcePositionAbs&&c.css("position","absolute");a.forceTextLeft&&c.css("text-align",
"left");a.forceNoWrap&&c.css("white-space","nowrap");if(a.relativeXOnResize){var f=c.offset().left-b(window).width()/2;if(typeof a.relativeXOnResize=="number")f=a.relativeXOnResize,c.css("left",b(window).width()/2+f);b(window).resize(function(){c.css("left",b(window).width()/2+f)})}if(a.slide){a.slideDuration=a.slideDuration||200;var d=parseInt(c.css("top")),k=d+b(document).scrollTop()+"px";c.animate({top:k},{duration:a.slideDuration,queue:!1});b(window).scroll(function(){k=d+b(document).scrollTop()+
"px";c.animate({top:k},{duration:a.slideDuration,queue:!1})})}if(a.autoPadLinksRight){var i,j,l=[];switch(typeof a.autoPadLinksRight){case "string":j=i=a.autoPadLinksRight;break;case "object":i=a.autoPadLinksRight.measureSelector;j=a.autoPadLinksRight.paddingSelector;break;default:j=i="a"}c.find(i).each(function(){l.push(b(this).width())});var h=Math.max.apply(Math,l);c.find(j).each(function(a){b(this).css("padding-right",h-l[a]+parseInt(b(this).css("padding-right")))})}a.fadeIn&&(c.css("display",
"none").css("visibility","visible"),c.delay(a.fadeInDelay).fadeIn(a.fadeIn));if(a.sectHiliteClass||a.linkHiliteClass||a.sectHiliteMap||a.linkHiliteMap){var g=[];c.find('a[href^="#"]').each(function(a){g[a]=b(this).attr("href")});if(a.sectHiliteClass||a.linkHiliteClass){var e=null;c.find('a[href^="#"]').click(function(){e=b(this).attr("href");a.linkHiliteClass&&(c.find('a[href^="#"]').removeClass(a.linkHiliteClass),b(this).addClass(a.linkHiliteClass));a.sectHiliteClass&&(b.each(g,function(c,d){b(d).removeClass(a.sectHiliteClass)}),
b(e).addClass(a.sectHiliteClass))});!a.persistentHilite&&a.smoothAnchors&&b(document).click(function(){b(e).click(function(a){a.stopPropagation()});e=null;c.find('a[href^="#"]').removeClass(a.linkHiliteClass);b.each(g,function(c,d){b(d).removeClass(a.sectHiliteClass)})})}if(a.sectHiliteMap||a.linkHiliteMap){var m=null,n=null,e=null;b('a[href^="#"]').first();a.linkHiliteMap&&(m=o(a.linkDefaultMap,a.linkHiliteMap)||q(a.linkHiliteMap));a.sectHiliteMap&&(n=o(a.sectDefaultMap,a.sectHiliteMap)||q(a.sectHiliteMap));
a.linkDefaultMap&&c.find('a[href^="#"]').css(a.linkDefaultMap);a.sectDefaultMap&&b.each(g,function(c,d){b(d).css(a.sectDefaultMap)});c.find('a[href^="#"]').click(function(){e=b(this).attr("href");a.linkHiliteMap&&(c.find('a[href^="#"]').css(m),b(this).css(a.linkHiliteMap));a.sectHiliteMap&&(b.each(g,function(a,c){b(c).css(n)}),b(e).css(a.sectHiliteMap))});!a.persistentHilite&&a.smoothAnchors&&b(document).click(function(){b(e).click(function(a){a.stopPropagation()});e=null;c.find('a[href^="#"]').css(m);
b.each(g,function(a,c){b(c).css(n)})})}}})}})(jQuery);